### ISSUE TITLE
Translation Exception : Illegal tag name DOI .

### ISSUE THREAD

**Issue by gph82** [enricobacis/wos#11]
Hi! 

Thanks for the python client. Any hints as to why this could not be working?
 ```
wos query DOI=10.1002/cphc.200800454 
Authenticated (SID: 1WMK4z2rCvoMTkBahe7)
ERROR: (QEE0001) The SOAP request message is invalid. Reason: The userQuery element is invalid. Cause: Translation Exception : Illegal tag name DOI
. Remedy: Correct your request and submit it again.
```
It's not exactly the same issue as here, i believe, but perhaps looking at it might help:
https://github.com/QUTlib/citation-import/issues/17

Thanks

**Comment by enricobacis** [comment]
Hi @gph82 

In the [field tags](http://ipscience-help.thomsonreuters.com/wosWebServicesLite/WebServiceOperationsGroup/WebServiceOperations/g2/user_query/field_tags/WOSfieldTags.html) documentation page of the service (linked in the readme), you can see that the field tag for the DOI is just `DO`, so your query should be:

    wos query 'DO=10.1002/cphc.200800454'
    <records>
        <REC r_id_disclaimer="ResearcherID data provided by Thomson Reuters">
            <UID>WOS:000261721700016</UID>
                ....
