### ISSUE TITLE
Queries for overly large records hang forever

### ISSUE THREAD

**Issue by nemobis** [enricobacis/wos#13]
Try querying for DO=10.1088/1748-0221/3/08/S08004 (http://oadoi.org/10.1088/1748-0221/3/08/S08004 ). Perhaps unsurprisingly, given it's one of those CERN LHC papers with thousands of authors, the request takes forever and ultimately fails. It might be good to add some super-cautious timeout, say 10 minutes.

**Comment by enricobacis** [comment]
I just committed the change that permits to specify the timeout (and also sets the default timeout to 600 seconds). Let me know if it works now.
