### ISSUE TITLE
Premium  API - High RAM usage

### ISSUE THREAD

**Issue by isezen** [enricobacis/wos#24]
Hello,

I'm downloading almost 19K publications from Web Service 100 by 100 and also saving each 100 records to a file instead of adding them to a list. If I don't 'import gc' and use 'gc.collect()' in for-loop, used RAM amount continuously increasing up to 5 or 6 GB. What would be the cause of this behavior?

**Comment by enricobacis** [comment]
Hi @isezen, normally the use of `gc.collect()` just forces the garbage collection to be executed when the line is processed, but the GC should still be invoked also without having to explicitly forcing it to happen. A general memory leak in fact is not normally solved with `gc.collect()` because it is a signal of the fact that someone still holds a reference to an object, so it's really peculiar that your case is different. Can I see your loop?

**Comment by isezen** [comment]
The total downloaded data size is approximately 1.35 GB. The code example below demonstrates how the RAM increases in for loop. Also at the end of process, in my opinion, RAM used by the app is still high even if I don't save any downloaded data into a variable. I see that regular expressions in the `single` function bumps the RAM but also without them, by using `search` function, RAM still increases. I suspect that this might be related to `suds` but I want to consult you first. Also, please, watch used RAM especially after 18000th record.
 
```python
from wos import WosClient
import wos.utils


def query(wosclient, wos_query, xml_query=None, count=5, offset=1, limit=100):
    """A modified version of wos.utils.query"""
    tot = 0
    for x in range(offset, count+1, limit):
        # I don't use a list comprehension here to make sure
        # that downloaded records are not accumulated.

        # MAX.VIRT.MEM: 2.3 GB
        wosclient.search(wos_query, min(limit, count - x + 1), x)

        # or try the code below

        # MAX.VIRT.MEM: 5.4 GB
        # wos.utils.single(wosclient, wos_query, xml_query,
        #                  min(limit, count - x + 1), x)

        tot += offset + min(limit, count - x + 1) - 1
        perc = tot * 100 / count
        print('Download : {} of {} [%{:2.1f}]'.format(tot, count, perc))


q = 'OO=istanbul tech univ'
with WosClient('user', 'pswd') as client:
    ret = client.search(q, count=0)
    query(client, q, count=ret.recordsFound)
```

Out of question: Why don't you use `retrieve` function in `query` and `single` functions to fetch consecutive records?

**Comment by zilyaJ** [comment]
Hello,

Can I ask how did you download the searching results? I don't know how to download it to local service since it's fullRecordSearchResults type.

**Comment by enricobacis** [comment]
This has been open for a while and I'm not sure if someone else is experiencing this. Feel free to re-open if relevant
