### ISSUE TITLE
Server raised fault: 'Not authorized for product: WWS' Follow Up

### ISSUE THREAD

**Issue by SebastianWeide** [enricobacis/wos#25]
Dear all,

I get the same error message ( 'Not authorized for product: WWS') that is mentioned in the closed thread using shibboleth by Technische Universität Berlin. So my question is if anybody has ever been successful with shibboleth from his or her institution. It seems to me that TU Berlin has premium access: http://rzblx10.uni-regensburg.de/dbinfo/detail.php?bib_id=tubb&colors=&ocolors=&lett=fs&tid=0&titel_id=3366

Regards,

Sebastian

**Comment by enricobacis** [comment]
I suggest you to contact the Web of Science support team and ask them if you have WWS access (it's a specific access that your university has to ask and pay for, it's not just the website access).
