### ISSUE TITLE
WebFault exception for frequent requests

### ISSUE THREAD

**Issue by skononov** [enricobacis/wos#27]
### Prerequisites

Make sure these boxes are checked before filling an issue

* [v] This issue is not the `No matches returned for Username or IP` 
  connection problem detailed [here](https://github.com/enricobacis/wos#faq-i-cannot-connect-)
* [v] I can reproduce the problem
* [v] I am running the latest version

### Version

0.1.15

### Description

suds.WebFault exception is thrown with a descritpion like below if WoS API requests happen too frequently. This is an obvious limitation of API and can be easily handled on the client side by pausing between requests (`threading` package from standard library may be used).

Example of exception description: 
`'Server raised fault: \'Request denied by Throttle server. Request denied for quantity of 1 for activity "Requests" of service "WOK-WS" for id "d5d9aa3b87cfc9d7d8c20b699bbf5bb5.55285" on Thursday, March 29, 2018 at 1:54:46 PM UTC.  The following reasons apply:   Reason (1) - limit of 2 requests per period has been exceeded for throttle REQ-ReqPerSec. Details of this throttle are the following : this is a RequestPerPeriod throttle; the period length is 1 second(s); the period restarts after Thursday, March 29, 2018 at 1:54:46 PM UTC.\''`

### Steps to Reproduce
import suds, wos
wos_client = WosClient(...)
wos_client.connect()
for i in range(10): 
    try:
        wos_client.retrieveById('WOS:000418267300045')
    except suds.WebFault:
        print('\nWebFault thrown at step',i)
        break

**Comment by enricobacis** [comment]
Can you try the current master version? It should address the problem.

Let me know if it works for you so that I can push a new version on PyPI.
