### ISSUE TITLE
Please add the Hot = On option to citedReferences retrieveParameters

### ISSUE THREAD

**Issue by meitiv** [enricobacis/wos#28]
### Prerequisites

Make sure these boxes are checked before filling an issue

* [x] This issue is not the `No matches returned for Username or IP` 
  connection problem detailed [here](https://github.com/enricobacis/wos#faq-i-cannot-connect-)
* [x] I can reproduce the problem
* [x] I am running the latest version

### Version

[You can get this information from executing `pip show wos`]

### Description

I would like to be able to see the Hot metadata of the citedRefernces (i.e. whether they are indexed in WoS)  For this to happen the retrieveParameters needs to have an option like so:

http://ipscience-help.thomsonreuters.com/wosWebServicesExpanded/WebServiceOperationsGroup/WSPremiumOperations/wokSearchGroup/citedReferences.html

But when I add a line 

            ('option', _OrderedDict([('key', 'Hot'), ('value', 'On')])),

to make_retrieveParameters()
I get an error:

suds.WebFault: b"Server raised fault: 'Unmarshalling Error: cvc-complex-type.2.4.a: Invalid content was found starting with element 'sortField'. One of '{option}' is expected. '"

I can remove the sortField from retrieveParameters and citedReferences works but then other methods break.

### Steps to Reproduce

1. [First Step]
2. [Second Step]
3. [and so on...]

**Expected behavior:** [What you expected to happen]

**Actual behavior:** [What actually happened]

**Comment by enricobacis** [comment]
Not sure if this is still relevant, feel free to re-open if needed. Thanks!
