### ISSUE TITLE
How to properly register wos with Clarivate?

### ISSUE THREAD

**Issue by rcwelsh** [enricobacis/wos#32]
### Prerequisites

Make sure these boxes are checked before filling an issue

* [X ] This issue is not the `No matches returned for Username or IP` 
  connection problem detailed [here](https://github.com/enricobacis/wos#faq-i-cannot-connect-)
* [X ] I can reproduce the problem
* [X ] I am running the latest version

### Version

pip show wos
Name: wos
Version: 0.1.15
Summary: Web of Science client using API v3.
Home-page: http://github.com/enricobacis/wos
Author: Enrico Bacis
Author-email: enrico.bacis@gmail.com
License: MIT
Location: /anaconda3/lib/python3.7/site-packages
Requires: suds-py3
Required-by:

### Description

I need to register the app with Clarivate (which is Thomas Reuters) in order to have access to the API. 

They ant the following questions answered:

1) Application ID: 
2) Application Name: 
3) Application Description
4) Client type
5) Y/N This application will use OAuth2.0 Flows

My answers:

1) wos
2) SOAP Client for querying the Web of Science database
3) Web of Science (previously Web of Knowledge) is an online subscription-based scientific citation indexing service maintained by Thomson Reuters. wos is a python SOAP Client (both API and command-line tool) to query the WOS database in order to get XML data from a query using the WWS access.
4) selected "Confidential: Server side application, can keep secrets confidential", other option are, "Public: Single Page Application (browser based app)" or "Public:  Native/Mobile Application (Android/iOS app)
5) unsure on this option.

### Steps to Reproduce

Can't get past hand shake due to need to register. I am in side the University of Utah firewall which does give us unlimited access to WoS.

**Expected behavior:** [What you expected to happen]

**Actual behavior:** [What actually happened]

screen shot attached.

![Screen Shot 2019-09-09 at 10 06 07 AM](https://user-images.githubusercontent.com/1485912/64547356-a0e3b000-d2e9-11e9-9ad4-f6ab5edbecff.png)

**Comment by gneissone** [comment]
@rcwelsh Your Web of Science subscription is separate from the API subscription and not tied to the university's network. You likely need to talk to someone in your library to get the username and password. Additionally, the SOAP API this library uses is an older version of the API that is not managed through the Clarivate Developer portal, so there's no need to register an application there.

**Comment by enricobacis** [comment]
Not sure if this is still relevant, feel free to re-open if needed. Thanks!
