### ISSUE TITLE
More encoding issues (?)

### ISSUE THREAD

**Issue by bjohas** [enricobacis/wos#33]
### Version

Name: wos
Version: 0.2.3
Summary: Web of Science client using API v3.
Home-page: http://github.com/enricobacis/wos
Author: Enrico Bacis
Author-email: enrico....
License: MIT
Location: /home/.../.local/lib/python2.7/site-packages
Requires: limit, suds
Required-by: 

### Description

I think i've got the same or a related issue as described here: https://github.com/enricobacis/wos/issues/31
The examples suggested there do work for me (but also doesn't seem to produce cyrillic characters - maybe the search order has changed), but I've got an issue with the query below.

### Steps to Reproduce

This works:
 wos -s ... query "TS=Côte"  -c0

This 
 wos -s ... query "TS=Côte"  -c1
does not.

**Expected behavior:** 
Expect results to be returned with utf characfers suitably encoded.

**Actual behavior:**
ERROR: 'ascii' codec can't decode byte 0xc3 in position 4: ordinal not in range(128)

I've reviewed this http://blog.mathieu-leplatre.info/python-utf-8-print-fails-when-redirecting-stdout.html and https://wiki.python.org/moin/PrintFails, and my terminal is set to UTF-8.

Any tips as to what might be going wrong?

**Comment by enricobacis** [comment]
Thanks for submitting this. I was not testing for unicode characters in the query. It should be fixed in 0.2.4 (which should be available in ~10 minutes from PyPI).

**Comment by bjohas** [comment]
Thanks for looking at this - I've just tried it, but get the same error.

Would you be able to have another look?

**Comment by enricobacis** [comment]
Are you sure that you updated the library? Because I tried the exact
command.

**Comment by bjohas** [comment]
Many thanks - fixed it!

I had the new library, but I had used the client from within another script, which suffered from the same problem!

Many thanks!

**Comment by enricobacis** [comment]
Perfect, cool!
