### ISSUE TITLE
SAXParseException: <unknown>:1:0: syntax error

### ISSUE THREAD

**Issue by echoyuu** [enricobacis/wos#35]
When I ran this demo ,I have revived this error , I don't why

In a few day, i connect with wos staff, check for the username and password of  wos lite api, and i use 

ti = 'DO=10.1016/j.biortech.2019.122174'
# https://wos.readthedocs.io/en/latest/documentation/client.html
with WosClient('S**_Univ', 'L**',lite=True) as wos:
    results = wos.search(ti)
succeed ,it return the value ,

but in a one day ,i use this code ,I have the error:
SAXParseException: <unknown>:1:0: syntax error

I don't know why , can someone help me

**Comment by enricobacis** [comment]
Not sure if this is still relevant, feel free to re-open if needed. Thanks!
