### ISSUE TITLE
Silent mode

### ISSUE THREAD

**Issue by mebibou** [enricobacis/wos#36]
### Prerequisites

Make sure these boxes are checked before filling an issue

* [x] This issue is not the `No matches returned for Username or IP` 
  connection problem detailed [here](https://github.com/enricobacis/wos#faq-i-cannot-connect-)
* [x] I can reproduce the problem
* [x] I am running the latest version

### Version

0.2.5

### Description

When running, there is always a log showing `b'Authenticated (SID:<id>)'`, could we have an option to silent that?

### Steps to Reproduce

1. [First Step]
2. [Second Step]
3. [and so on...]

**Expected behavior:** [What you expected to happen]

**Actual behavior:** [What actually happened]

**Comment by enricobacis** [comment]
Sure, I think it makes sense. I think that we can use the `verbose` flag that is already there.

It should only print the message if: the `verbose` flag is set OR the `connect` option was used (because in that case the SID is actually the output).

Feel free to send a PR and I'll merge it.

**Comment by gmella** [comment]
I guess that PR #38 should do the job.
