### ISSUE TITLE
Querying additional databases (e.g. scopus)

### ISSUE THREAD

**Issue by 1kastner** [enricobacis/wos#39]
### Description

First of all great thanks for sharing your effort as a github project!

I wondered if there is a related project you have been working on or maybe you have heard of to combine the search results of different scientific literature APIs. That way, e.g. scopus and WoS could be used as two different databases for the same query to make sure not to accidentally skip some important results.

**Comment by enricobacis** [comment]
Hi, unfortunately not that I'm aware of. Feel free to re-open this and post some link if you discover some of these :)

**Comment by 1kastner** [comment]
Thank you very much for your information! Actually at https://github.com/pybliometrics-dev/pybliometrics/issues/190 there is an ongoing discussion about the same topic coming from scopus.
