### ISSUE TITLE
wos 0.2.6 fails to install from PyPI: FileNotFoundError: [Errno 2] No such file or directory: 'VERSION'

### ISSUE THREAD

**Issue by jdddog** [enricobacis/wos#41]
### Prerequisites

Make sure these boxes are checked before filling an issue

* [x] This issue is not the `No matches returned for Username or IP` 
  connection problem detailed [here](https://github.com/enricobacis/wos#faq-i-cannot-connect-)
* [x] I can reproduce the problem
* [x] I am running the latest version

### Version

wos version: 0.2.6
Python version: 3.6.9

### Description
The file `VERSION` is not built into the Python package on PyPI, resulting in an error when installing wos 0.2.6, which did not occur with wos 0.2.5. This prevents the package from installing. An example is below:
```bash
user@computer:~$ pip3 install wos==0.2.6
Defaulting to user installation because normal site-packages is not writeable
Collecting wos==0.2.6
  Downloading wos-0.2.6.tar.gz (12 kB)
    ERROR: Command errored out with exit status 1:
     command: /usr/bin/python3 -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-o6xktopr/wos/setup.py'"'"'; __file__='"'"'/tmp/pip-install-o6xktopr/wos/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base /tmp/pip-pip-egg-info-herr4d_9
         cwd: /tmp/pip-install-o6xktopr/wos/
    Complete output (5 lines):
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-install-o6xktopr/wos/setup.py", line 8, in <module>
        with open('VERSION') as VERSION:
    FileNotFoundError: [Errno 2] No such file or directory: 'VERSION'
    ----------------------------------------
ERROR: Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.
```

### Steps to Reproduce

1. `pip3 install wos==0.2.6`

**Expected behavior:** [What you expected to happen]

The package installs.

**Actual behavior:** [What actually happened]

The package does not install.

**Comment by enricobacis** [comment]
Thanks, I made 0.2.5 the default for now, so

`pip3 install wos` will pull version 0.2.5

I yanked (https://pypi.org/help/#yanked) 0.2.6 on PyPI, so when the version is pinned (`pip3 install wos==0.2.6`) it will still get the broken package, but a normal `pip3 install wos` will work.
